#!/bin/zsh
##? brewls - List top level brew installs.
echo "==> Root Formulae"
brew deps --installed --formula | \
    awk -F'[: ]+' \
    '{
        packages[$1]++
        for (i = 2; i <= NF; i++)
            dependencies[$i]++
    }
    END {
        for (package in packages)
            if (!(package in dependencies))
                print package
    }' | \
    sort | column
echo "\n==> Casks"
brew list --cask
