#!/bin/zsh

##? bindkey-all - run bindkey for all of the keymaps
##?
##? Run with no arguments to print out all keymaps.
function bindkey-all {
  local keymap=''
  for keymap in $(bindkey -l); do
    [[ "$#" -eq 0 ]] && printf "#### %s\n" "${keymap}" 1>&2
    bindkey -M "${keymap}" "$@"
  done
}
bindkey-all "$@"
