#!/bin/zsh

##? expand-dot-to-parent-directory-path - expand .... to ../..
function expand-dot-to-parent-directory-path {
  if [[ $LBUFFER = *.. ]]; then
    LBUFFER+='/..'
  else
    LBUFFER+='.'
  fi
}
expand-dot-to-parent-directory-path "$@"
