#!/bin/zsh

##? Make your enter key magical by binding a Zsh command to it
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/magic-enter

# function magic-enter {
# Only run MAGIC_ENTER commands when in PS1 and command line is empty
# http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#User_002dDefined-Widgets
if [[ -n "$BUFFER" || "$CONTEXT" != start ]]; then
  return
fi

local cmd
if (( $+functions[magic-enter-command] )); then
  cmd=$(magic-enter-command)
elif command git rev-parse --is-inside-work-tree &>/dev/null; then
  zstyle -s ':zephyr:plugin:editor:magic-enter' git-command 'cmd' \
    || cmd="${MAGIC_ENTER_GIT_COMMAND:-git status -sb .}"
else
  zstyle -s ':zephyr:plugin:editor:magic-enter' git-command 'cmd' \
    || cmd="${MAGIC_ENTER_OTHER_COMMAND:-ls .}"
fi
BUFFER="$cmd"
# }
