#!/bin/zsh
##? Toggle the comment character at the start of the line. This is meant to work
##? around a buggy implementation of pound-insert in zsh.
##?
##? This is currently only used for the emacs keys because vi-pound-insert has
##? been reported to work properly.
# function pound-toggle {
if [[ "$BUFFER" = '#'* ]]; then
  # Because of an oddity in how zsh handles the cursor when the buffer size
  # changes, we need to make this check before we modify the buffer and let
  # zsh handle moving the cursor back if it's past the end of the line.
  if [[ $CURSOR != $#BUFFER ]]; then
    (( CURSOR -= 1 ))
  fi
  BUFFER="${BUFFER:1}"
else
  BUFFER="#$BUFFER"
  (( CURSOR += 1 ))
fi
# }
