#!/bin/zsh
##? Autoload all function files in a directory.
#function autoload-dir {
  emulate -L zsh; setopt local_options extended_glob
  local zdir zautoloads=()
  for zdir in $@; do
    [[ -d $zdir ]] || continue
    fpath=($zdir $fpath)
    zautoloads=($zdir/*~_*(N.:t))
    (( ${#zautoloads} > 0 )) && autoload -Uz $zautoloads
  done
#}
