#!/bin/zsh

##? zephyr-autoload-dir - Autoload all Zephyr functions in a dir.

#function zephyr-autoload-dir
[[ -d "$1" ]] || return 1
fpath+="$1"
local fn
for fn in "$1"/*(.N); do
  autoload -Uz $fn
done
#}
