#!/usr/bin/env zsh
0=${(%):-%x}
ZEPHYR_HOME=${ZEPHYR_HOME:-${0:A:h:h}}
cmd="$1"

if (( $+functions[zephyr-${cmd}] )); then
  zephyr-${cmd} "$@"
  return $?
elif [[ -z "$cmd" ]] || [[ $cmd = (--help|-h) ]]; then
  zephyr-help "$@"
elif [[ $cmd = (--version|-v) ]]; then
  local ver="0.0.2"
  local gitsha=$(git -C "${0:h:h}" rev-parse --short HEAD 2>/dev/null)
  [[ -z "$gitsha" ]] || ver="$ver ($gitsha)"
  echo "zephyr version $ver"
else
  echo >&2 "zephyr: command not found '${cmd}'" && return 1
fi
