#!/usr/bin/env zsh
0=${(%):-%x}
ZEPHYR_HOME=${ZEPHYR_HOME:-${0:A:h:h}}

local repos=(
  # core
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-completions
  zsh-users/zsh-history-substring-search

  # utils
  romkatv/zsh-bench
  romkatv/gitstatus

  # syntax highlighting
  zdharma-continuum/fast-syntax-highlighting
  zsh-users/zsh-syntax-highlighting

  # prompts
  sindresorhus/pure
  romkatv/powerlevel10k
  dracula/zsh
  ohmyzsh/ohmyzsh
)

local repo plugin_dir
for repo in $repos; do
  plugin_dir=$ZEPHYR_HOME/.external/${repo:h}/${repo:t}
  if [[ ! -d $plugin_dir ]]; then
    echo "Zephyr cloning dependencies: ${repo}..."
    git clone -q --depth 1 --recursive --shallow-submodules https://github.com/$repo $plugin_dir
  fi
done
