#!/bin/zsh
#function zephyr-update-submodles {
emulate -L zsh

0=${(%):-%x}
ZEPHYR_HOME=${ZEPHYR_HOME:-${0:A:h:h}}
git pull --recurse-submodules
git submodule update --remote --recursive
echo "Zephyr submodule update complete."
#}
