#!/bin/zsh

##? funchelp - use '##?' comments in function files as help docs.
##?
##? usage: funchelp <func>

#function funchelp {

local ZFUNCDIR="${ZFUNCDIR:-${ZDOTDIR:-~/.config/zsh}/functions}"
if [[ ! -f "$ZFUNCDIR/$1" ]]; then
  echo >&2 "funchelp: function not found '$1'." && return 1
fi
command grep "^##?" "$ZFUNCDIR/$1" | cut -c 5-

#}
