#!/bin/zsh
function pbcopy {
  # Fallback for missing pbcopy command.
  if (( $+commands[pbcopy] )); then
    command pbcopy "$@"
  elif [[ "$OSTYPE" == (cygwin|msys)* ]]; then
    tee > /dev/clipboard
  elif (( $+commands[clip.exe] )) && (( $+commands[powershell.exe] )); then
    clip.exe
  elif [ -n $WAYLAND_DISPLAY ] && (( ${+commands[wl-copy]} )) && (( ${+commands[wl-paste]} )); then
    wl-copy
  elif [ -n $DISPLAY ] && (( ${+commands[xsel]} )); then
    xsel --clipboard --input
  elif [ -n $DISPLAY ] && (( ${+commands[xclip]} )); then
    xclip -selection clipboard -in
  elif (( ${+commands[win32yank]} )); then
    win32yank -i
  elif [[ $OSTYPE == linux-android* ]] && (( $+commands[termux-clipboard-set] )); then
    termux-clipboard-set
  elif [ -n $TMUX ] && (( ${+commands[tmux]} )); then
    tmux load-buffer
  fi
}
pbcopy "$@"
