#!/bin/zsh
#function zephyr-clone {
emulate -L zsh; setopt local_options extended_glob no_monitor
0=${(%):-%x}

local extdir=${0:A:h:h:h}/.external
local repo plugindir initfile
for repo in $@; do
  plugindir=${extdir}/${repo:t}
  initfile=${plugindir}/init.zsh
  if [[ ! -d $plugindir ]]; then
    echo "Zephyr cloning $repo..."
    {
      git clone -q --depth 1 --recursive --shallow-submodules https://github.com/$repo $plugindir
      if [[ ! -e $initfile ]]; then
        local -a pluginfiles=($plugindir/*.plugin.{z,}sh(N) $plugindir/*.{z,}sh{-theme,}(N))
        (( $#pluginfiles )) && ln -sf "${pluginfiles[1]}" "$initfile"
      fi
    } &
  fi
done
wait
#}
