#!/bin/zsh
#function zephyr-updatecheck {
emulate -L zsh; setopt local_options extended_glob
local cache_dir=${XDG_CACHE_HOME:=$HOME/.cache}/zephyr
local lastupdated="$cache_dir/lastupdated"
if [[ ! -f "$lastupdated" ]]; then
  mkdir -p "${lastupdated:h}"
  date '+%Y-%m-%d %H:%M:%S' >"$lastupdated"
fi

# Test by changing date on .lastupdated file.
# touch -a -m -t 200101010909.09 "$XDG_CACHE_HOME/zephyr/lastupdated"
local -a oldfiles=($lastupdated(Nmw+1))
(( $#oldfiles )) && zephyr-update
#}
