#!/bin/zsh
0=${(%):-%x}

# show exit code on right
function precmd_pipestatus {
  local exitcodes="${(j.|.)pipestatus}"
  if [[ "$exitcodes" != "0" ]]; then
    RPROMPT="%F{$prompt_pure_colors[prompt:error]}[$exitcodes]%f"
  else
    RPROMPT=
  fi
}
add-zsh-hook precmd precmd_pipestatus

fpath+=${0:h:h}/external/pure
source ${0:h:h}/external/pure/pure.zsh
