#!/bin/zsh
function prompt_starship_setup {
  0=${(%):-%x}

  if ! (( $+commands[starship] )); then
    # We could install, but running a remotely hosted shell script is not a risk
    # Zephyr should assume. Let's let the user decide whether to install it.
    echo >&2 "Starship prompt not installed. See https://starship.rs to install."
    return 1
  fi

  # When loaded through the prompt command, these prompt_* options will be enabled
  prompt_opts=(cr percent sp subst)

  # Set the starship config based on the argument if provided.
  local prompt_config="$1"
  if [[ -n "$prompt_config" ]]; then
    local -a configs=(
      ${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/themes/${prompt_config}.toml(N)
      ${XDG_CONFIG_HOME:-$HOME/.config}/starship/${prompt_config}.toml(N)
      ${0:A:h:h}/themes/${prompt_config}.toml(N)
    )
    if (( $#configs )); then
      export STARSHIP_CONFIG=$configs[1]
    else
      unset STARSHIP_CONFIG
    fi
  fi

  local starship_init=${XDG_CACHE_HOME:-~/.cache}/zephyr/starship_init.zsh
  [[ -d $starship_init:h ]] || mkdir -p $starship_init:h

  local cache=($starship_init(Nmh-20))
  (( $#cache )) || starship init zsh --print-full-init >| $starship_init
  source $starship_init
}
prompt_starship_setup "$@"
