#!/bin/zsh
#
# clippaste - Paste data from clipboard to stdout
#
#
# Usage:
#   clippaste               - writes clipboard's contents to stdout
#   clippaste | <command>   - pastes contents and pipes it to another process
#   clippaste > <file>      - paste contents to a file
#
# Examples:
#   # Pipe to another process
#   clippaste | grep foo
#
#   # Paste to a file
#   clippaste > file.txt
#

function clippaste {
  if detect-clipboard; then
    clippaste "$@"
  else
    print "clippaste: Platform $OSTYPE not supported or xclip/xsel not installed" >&2
    return 1
  fi
}
clippaste "$@"
