#!/bin/zsh
#
# clipcopy - Copy data to clipboard
#
# Usage:
#  <command> | clipcopy    - copies stdin to clipboard
#  clipcopy <file>         - copies a file's contents to clipboard
#

function clipcopy {
  if detect-clipboard; then
    clipcopy "$@"
  else
    print "clipcopy: Platform $OSTYPE not supported or xclip/xsel not installed" >&2
    return 1
  fi
}
clipcopy "$@"
