#!/bin/zsh
##? copypath - Copy the path to clipboard or current directory if no parameter.

#function copypath {
  # If no argument passed, use current directory.
  local file="${1:-.}"

  # If argument is not an absolute path, prepend $PWD.
  [[ $file = /* ]] || file="$PWD/$file"

  # Copy the absolute path without resolving symlinks
  # If clipcopy fails, exit the function with an error
  print -n "${file:a}" | clipcopy || return 1

  echo ${(%):-"%B${file:a}%b copied to clipboard."}
#}
